# Generated by Django 4.2.10 on 2024-11-10 00:41

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(max_length=500)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('experience_level', models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level'), ('Executive', 'Executive')], max_length=20)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Human Resources', 'Human Resources'), ('Engineering', 'Engineering'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Customer Service', 'Customer Service'), ('Sales', 'Sales'), ('Project Management', 'Project Management'), ('Design', 'Design'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Research', 'Research'), ('Legal', 'Legal'), ('Public Relations', 'Public Relations'), ('Food Service', 'Food Service'), ('Travel', 'Travel'), ('Real Estate', 'Real Estate'), ('Media', 'Media'), ('Art', 'Art'), ('Music', 'Music'), ('Fitness', 'Fitness'), ('Sports', 'Sports'), ('Government', 'Government'), ('Non-Profit', 'Non-Profit'), ('Other', 'Other')], max_length=50)),
                ('education_level', multiselectfield.db.fields.MultiSelectField(choices=[('High School Diploma', 'High School Diploma'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate Degree', 'Doctorate Degree'), ('Professional Certification', 'Professional Certification'), ('Vocational Training', 'Vocational Training'), ('On-the-job Training', 'On-the-job Training'), ('No Degree Required', 'No Degree Required'), ('Other', 'Other')], max_length=50)),
                ('industry', multiselectfield.db.fields.MultiSelectField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Hospitality', 'Hospitality'), ('Construction', 'Construction'), ('Media', 'Media'), ('Government', 'Government'), ('Non-Profit', 'Non-Profit'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('remote_work', multiselectfield.db.fields.MultiSelectField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('job_features', multiselectfield.db.fields.MultiSelectField(choices=[('Flexible Schedule', 'Flexible Schedule'), ('Competitive Salary', 'Competitive Salary'), ('Medical Insurance', 'Medical Insurance'), ('Dental Insurance', 'Dental Insurance'), ('Vision Insurance', 'Vision Insurance'), ('401(k) Retirement Plan', '401(k) Retirement Plan'), ('Paid Time Off', 'Paid Time Off'), ('Paid Sick Leave', 'Paid Sick Leave'), ('Tuition Reimbursement', 'Tuition Reimbursement'), ('Professional Development', 'Professional Development'), ('Relocation Assistance', 'Relocation Assistance'), ('Employee Discounts', 'Employee Discounts'), ('Company Events', 'Company Events'), ('Work-Life Balance', 'Work-Life Balance'), ('Career Growth Opportunities', 'Career Growth Opportunities'), ('Mentoring Program', 'Mentoring Program'), ('Employee Recognition Program', 'Employee Recognition Program'), ('Employee Assistance Program', 'Employee Assistance Program'), ('Other', 'Other')], max_length=200)),
            ],
        ),
    ]
